#!/bin/bash

RETRY=${RETRY:-"2s"}
INTERVAL=${INTERVAL:-"5m"}

if [[ "${LOG_LEVEL}" == "trace" ]]
then
  LOG_LEVEL=0
elif [[ "${LOG_LEVEL}" == "debug" ]]
then
  LOG_LEVEL=1
elif [[ "${LOG_LEVEL}" == "information" || "${LOG_LEVEL}" == "info" ]]
then
  LOG_LEVEL=2
elif [[ "${LOG_LEVEL}" == "warning" || "${LOG_LEVEL}" == "warn" ]]
then
  LOG_LEVEL=3
elif [[ "${LOG_LEVEL}" == "error" ]]
then
  LOG_LEVEL=4
elif [[ "${LOG_LEVEL}" == "critical" || "${LOG_LEVEL}" == "crit" ]]
then
  LOG_LEVEL=5
elif [[ "${LOG_LEVEL}" == "none" || "${LOG_LEVEL}" == "silent" ]]
then
  LOG_LEVEL=6
else
  LOG_LEVEL=0
fi

RESET="\e[0m"
BOLD="\e[1m"
DIM="\e[2m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
PURPLE="\e[35m"
DARK_GRAY="\e[90m"

log-timestamp () {
  echo -ne "${DIM}$(date +"%Y-%m-%d %H:%M:%S%:z")${RESET} " >&2
}

log-success () {
  log-timestamp
  echo -e "${GREEN}DONE${RESET} ${GREEN}✓${RESET} $1" >&2
}

log-critical () {
  if [[ "${LOG_LEVEL}" -gt 5 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${PURPLE}CRIT${RESET} ${PURPLE}⭍${RESET} $1" >&2
}

log-error () {
  if [[ "${LOG_LEVEL}" -gt 4 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${RED}ERRO${RESET} ${RED}!${RESET} $1" >&2
}

log-warning () {
  if [[ "${LOG_LEVEL}" -gt 3 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${YELLOW}WARN${RESET} ${YELLOW}△${RESET} $1" >&2
}

log-information () {
  if [[ "${LOG_LEVEL}" -gt 2 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${BLUE}INFO${RESET} ${BLUE}○${RESET} $1" >&2
}

log-debug () {
  if [[ "${LOG_LEVEL}" -gt 1 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${DIM}DBUG *${RESET} $1" >&2
}

log-trace () {
  if [[ "${LOG_LEVEL}" -gt 0 ]]
  then
    return
  fi
  log-timestamp
  echo -e "${DIM}TRAC ↩${RESET} $1" >&2
}

failed-wait-and-retry() {
  if [[ -f /healthy ]]
  then
    rm /healthy
  fi
  log-debug "${BOLD}Retrying${RESET} in ${RETRY}"
  sleep "${RETRY}"
}

success-wait() {
  touch /healthy
  log-debug "${BOLD}Waiting${RESET} ${INTERVAL} before next run"
  sleep "${INTERVAL}"
}

# Validate environment variables
ISSUES=()
if [[ -z "${GLUETUN_API_PORT}" ]]
then
  GLUETUN_API_PORT=${GLUETUN_API_PORT:-"8000"}
  log-information "GLUETUN_API_PORT is not set. Defaulting to ${GLUETUN_API_PORT}"
fi
if [[ -z "${DELUGE_WEB_PORT}" ]]
then
  DELUGE_WEB_PORT=${DELUGE_WEB_PORT:-"8112"}
  log-information "DELUGE_WEB_PORT is not set. Defaulting to ${DELUGE_WEB_PORT}"
fi
if [[ -z "${DELUGE_PASSWORD}" ]]
then
  ISSUES+=("DELUGE_PASSWORD")
fi
if [[ "${#ISSUES[@]}" -gt 0 ]]
then
  log-error "Missing environment variables: ${ISSUES[*]}"
  log-critical "Unable to continue"
  sleep infinity
fi

while true
do
  log-information "${BOLD}Running${RESET} monitor"

  log-debug "${BOLD}Determining${RESET} forwarded port"
  JSON=$(curl --fail --silent --show-error "http://localhost:${GLUETUN_API_PORT}/v1/openvpn/portforwarded")
  PORT=$(echo "${JSON}" | jq -r '.port')
  if [[ "${PORT}" == "" ]]
  then
    log-error "Forwarded port is not defined"
    failed-wait-and-retry
    continue
  elif [[ -f /port && $(cat /port) == "${PORT}" ]]
  then
    log-debug "Port is already set to ${PORT}"
    success-wait
    continue
  fi

  log-debug "${BOLD}Authenticating${RESET} with API"
  JSON=$(curl --fail-with-body --silent \
    --header "Content-Type: application/json" \
    --data '{"method": "auth.login", "params": ["'"${DELUGE_PASSWORD}"'"], "id": '${RANDOM}'}' \
    --cookie-jar /tmp/deluge-cookie \
    "http://localhost:${DELUGE_WEB_PORT}/json")
  if [[ $(echo "${JSON}" | jq -r '.result') != "true" || $(echo "${JSON}" | jq -r '.error') != "null" ]]
  then
    log-error "${BOLD}Failed${RESET} to authenticate"
    log-trace "${JSON}"
    failed-wait-and-retry
    continue
  fi

  log-debug "${BOLD}Checking${RESET} daemon connection"
  JSON=$(curl --fail-with-body --silent \
    --header "Content-Type: application/json" \
    --data '{"method": "web.connected", "params": [], "id": '${RANDOM}'}' \
    --cookie /tmp/deluge-cookie \
    "http://localhost:${DELUGE_WEB_PORT}/json")
  if [[ $(echo "${JSON}" | jq -r '.result') != "true" || $(echo "${JSON}" | jq -r '.error') != "null" ]]
  then
    log-warning "Daemon is not connected. Will attempt to connect"
    log-trace "${JSON}"

    log-debug "${BOLD}Listing${RESET} daemons"
    JSON=$(curl --fail-with-body --silent \
      --header "Content-Type: application/json" \
      --data '{"method": "web.get_hosts", "params": [], "id": '${RANDOM}'}' \
      --cookie /tmp/deluge-cookie \
      "http://localhost:${DELUGE_WEB_PORT}/json")
    log-trace "${JSON}"
    if [[ $(echo "${JSON}" | jq -r '.error') != "null" ]]
    then
      log-error "${BOLD}Failed${RESET} to list daemons"
      log-trace "${JSON}"
      failed-wait-and-retry
      continue
    fi

    HOST_ID=$(echo "${JSON}" | jq -r '.result[0][0]')
    log-debug "${BOLD}Connecting${RESET} web client to daemon ${HOST_ID}"
    JSON=$(curl --fail-with-body --silent \
      --header "Content-Type: application/json" \
      --data '{"method": "web.connect", "params": ["'"${HOST_ID}"'"], "id": '${RANDOM}'}' \
      --cookie /tmp/deluge-cookie \
      "http://localhost:${DELUGE_WEB_PORT}/json")
    if [[ $(echo "${JSON}" | jq -r '.error') != "null" ]]
    then
      log-error "${BOLD}Failed${RESET} to connect web client to daemon"
      log-trace "${JSON}"
      failed-wait-and-retry
      continue
    fi
  fi

  log-debug "${BOLD}Setting${RESET} listen port"
  JSON=$(curl --fail-with-body --silent \
    --header "Content-Type: application/json" \
    --data '{"method": "core.set_config", "params": [{"listen_ports": ['"${PORT}"','"${PORT}"']}], "id": '${RANDOM}'}' \
    --cookie /tmp/deluge-cookie \
    "http://localhost:${DELUGE_WEB_PORT}/json")
  if [[ $(echo "${JSON}" | jq -r '.error') != "null" ]]
  then
    if [[ $(echo "${JSON}" | jq -r '.error.message') == "Unknown method" ]]
    then
      log-error "Daemon is probably not connected"
    else
      log-error "${BOLD}Failed${RESET} to set listen port"
    fi
    log-trace "${JSON}"
    failed-wait-and-retry
    continue
  fi

  log-success "${BOLD}Set${RESET} listen port to ${PORT}"
  touch /port
  echo "${PORT}" > /port
  success-wait
  continue
done

echo "Service terminated"

exit 1
